### ISSUE TITLE
Landing Page Lower Grey Section and Footer Responsives

### ISSUE THREAD

**Issue by daniel-cy-lu** [overture-stack/website#287]
Add css so the landing page lower grey section and footer have proper views at mobile and tablet width.

**Comment by daniel-cy-lu** [comment]
https://deploy-preview-284--overture.netlify.app/ @patrickdsantos

**Comment by patrickdsantos** [comment]
Well done Daniel! Some feedback below:

1.  Fix hamburger menu to match mockups: remove duplicate arrows, font set to 20px, logo is centred, 'X' is on the left side of the screen etc.
![Screenshot 2023-08-21 at 3 37 10 PM](https://github.com/overture-stack/website/assets/116736040/e7c4bcf3-2009-46ac-ae48-92743a6a4db6)

2. Center logo, swap hamburger icon to the one used in the mocks, move to left side of the screen and add "Get Started" button to the top right hand corner. 
![Screenshot 2023-08-21 at 4 13 32 PM](https://github.com/overture-stack/website/assets/116736040/44719b65-af29-48b2-97a4-122ddb470e63)

3. Similar feedback from ticket #289 , accommodate screens that are between 360px and 426px.
Right now, when the window is smaller than 426px wide, the hero copy and body copy are no longer centred and starts to cut off. 
![Screenshot 2023-08-21 at 3 53 38 PM](https://github.com/overture-stack/website/assets/116736040/6c4aa490-18bb-40c9-a741-51c877f83198)

4. Spacing with this illustration is still a bit off, will schedule time together to discuss solutions. (It's a tough illustration for responsive design, not your fault!!)
![Screenshot 2023-08-21 at 3 55 03 PM](https://github.com/overture-stack/website/assets/116736040/599a57c9-dc4b-4bdf-bccb-fb5a048e2932)

5. Similar feedback from ticket #288 , logos are pixelated
![Screenshot 2023-08-21 at 3 56 43 PM](https://github.com/overture-stack/website/assets/116736040/d0ef6c8e-d3f1-4678-b4d9-562e62c31aff)

6. This was not reflected in the mocks but this area looks a bit squished. Can we increase the padding in between these columns? (try adding additional 10px in between each)
![Screenshot 2023-08-21 at 3 58 46 PM](https://github.com/overture-stack/website/assets/116736040/81df51a3-30be-40ea-a36b-9c8008610e92)

7. Bold the CTA copy (this applies to all CTAs on the website)
![Screenshot 2023-08-21 at 3 31 21 PM](https://github.com/overture-stack/website/assets/116736040/31564e38-7fdf-4290-a732-a6debd53a1bd)

8. Change line-height of text to 36px
![Screenshot 2023-08-21 at 3 34 36 PM](https://github.com/overture-stack/website/assets/116736040/b56f73a4-6955-4dce-85dd-c33243ef28ea)

9. The space is little off here, can we get all components left aligned with the title?
![Screenshot 2023-08-21 at 4 02 02 PM](https://github.com/overture-stack/website/assets/116736040/a952ecf8-5591-4f13-a804-7bc63c51bba5)

10. These elements should stack in a single column, refer to mocks for direction.
![Screenshot 2023-08-21 at 4 17 39 PM](https://github.com/overture-stack/website/assets/116736040/307f8c87-5abb-4d9a-ba5e-2acdca4b617d)

11. These elements should be arranged in two columns, refer to mocks for direction.
![Screenshot 2023-08-21 at 4 19 27 PM](https://github.com/overture-stack/website/assets/116736040/8bc9f26b-e30b-4c88-86bf-93d1b3146368)

12. The spacing on the right side is strange, also reduce size of the image so that it's width is 450px.
![Screenshot 2023-08-21 at 4 21 24 PM](https://github.com/overture-stack/website/assets/116736040/3ef3647d-b340-4ed3-9dee-88013459400a)

13. Increase margin between arrow and image. Try 30px
![Screenshot 2023-08-21 at 4 28 37 PM](https://github.com/overture-stack/website/assets/116736040/fd9ce257-3a6a-4f03-a13f-8de8f45184f7)

14. Increase padding in between these elements. Try 30px
![Screenshot 2023-08-21 at 4 30 27 PM](https://github.com/overture-stack/website/assets/116736040/6067208f-9693-4e86-bc07-20e7d3f413c0)

15. Increase spacing between each column. Try 30px
![Screenshot 2023-08-21 at 4 32 56 PM](https://github.com/overture-stack/website/assets/116736040/e6aa62ce-5be3-48f0-96b9-a6cd19b7cdaf)

16. Add more padding between illustration and header copy. Try 30px
![Screenshot 2023-08-21 at 4 37 19 PM](https://github.com/overture-stack/website/assets/116736040/0250cafb-d334-4856-8406-5f51f7039b97)

**Comment by daniel-cy-lu** [comment]
1. @patrickdsantos I updated the navbar to represent the one in the mock up. The only thing I am having difficulty is I couldn't line up the second column under Products and DMS Bundle. I could get them to center. Here are six screenshots. They are of four different width, mobile, tablet, desktop and ultra wide. And I have both the toggled menu open and close for mobile and tablet[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazB5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c91345c83a804b79d4e5ddf33279a926081d2504/Screenshot%202023-08-23%20at%2010.36.42%20PM.png)
.[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazR5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--82e2f2004d3fb78e9d7c166eaeb828f302a6b956/Screenshot%202023-08-23%20at%2010.37.22%20PM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazh5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2464a948427558bc30911fa523a3020af2ace5bc/Screenshot%202023-08-23%20at%2010.54.59%20PM.png)

**Comment by daniel-cy-lu** [comment]
3 and 4. Fixed line-height and the left alignment of text. Here are two screenshots:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcEkxIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--008e2bf7d667006b3c8be0c26c8e7ecaa27a5149/Screenshot%202023-08-24%20at%2010.17.04%20AM.png)

**Comment by patrickdsantos** [comment]
Thanks Daniel, these are looking great! Providing just one more piece of feedback below but this can be completed post MVP:

Reduce padding above to match the bottom of the grey box
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWM5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--829bb54e910f4e37ad6b9f077d3da69863d49c97/Screenshot%202023-08-25%20at%2011.47.28%20AM.png)
